#!/bin/sh

# git version_reversion
# VERSION_REVISION=`git describe --abbrev=6 --always`
# VERSION_MAJOR=`grep VERSION_MAJOR CMakeLists.txt | sed -r 's/set\((.+) (.+)\)/\2/'`
# VERSION_MINOR=`grep VERSION_MINOR CMakeLists.txt | sed -r 's/set\((.+) (.+)\)/\2/'`
# VERSION_PATCH=`grep VERSION_PATCH CMakeLists.txt | sed -r 's/set\((.+) (.+)\)/\2/'`
# git tag v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_REVISION}
echo "Have you checked the VERSION setting?"
